import requests
# API call tested with and generated by Insomnia api client
url = "http://0.0.0.0:8081/interest"

payload = "{ \"message\": 1 , \"address\": \"4 Main Road, Mowbray, Cape Town, South Africa\", \"name\" : \"John Deer\" }"

response = requests.request("POST", url, data=payload, headers=headers)

print(response.text)
