import requests
# API call tested through and generated by Insomnia
url = "http://0.0.0.0:8081/interest"

payload = "{ \"message\": 1 , \"geometry\": {\"coordinates\":[\"-33.947272\",\"18.4783663\"]}, \"name\" : \"Jay Walker\" }\n"

response = requests.request("POST", url, data=payload, headers=headers)

print(response.text)
